### PR TITLE
Remove WordPress dependency

### PR DESCRIPTION
**Pull request by BrianHenryIE**
In order to use WP_Mock for unit tests, I replaced the WordPress functions being used with the content from the function definitions.

No breaking changes.

### CODE REVIEW

**Comment by pablo-sg-pacheco** [comment]
Hi @BrianHenryIE ,
Great! Thanks.

Shamely I don't have experience with WP_Mock or with testing in general.
I'd love to see some real exemple with this library. If you have it please let me know

**Comment by BrianHenryIE** [comment]
[Autologin URLs](https://github.com/BrianHenryIE/BH-WP-Autologin-URLs) is my project for learning best practices. I'm now including your project via Composer (you asked me previously why not). I include `wp-namespace-autoloader` into the Composer `vendor` directory, then use [Mozart](https://github.com/coenjacobs/mozart) to copy it to the plugin's source directory (I'm currently calling `trunk` to match the WordPress.org plugin SVN, but might soon change it to `src`) and to prefix the namespace to avoid collisions/race conditions (`class_exists` isn't adequate when I make so many changes to files I use across plugins!). Then I use `spl_autoload_register` to [autoload your autoloader](https://github.com/BrianHenryIE/BH-WP-Autologin-URLs/blob/master/trunk/autoload.php), and the PR to allow multiple `classes_dir` lets it autoload from the plugin root and from the plugin `vendor` folder.

I have [another branch in progress](https://github.com/pablo-sg-pacheco/wp-namespace-autoloader/compare/master...BrianHenryIE:wpcs) for you to change the code itself to be WPCS correct.

**Comment by BrianHenryIE** [comment]
I'm not sure the quality of my tests, but the coverage is high, which is hugely reassuring when messing around with the code.

**Comment by pablo-sg-pacheco** [comment]
Great @BrianHenryIE ! Thanks!
I struggled a lot to setup WPCS for Sublime, but never used it with Phpunit. I mean, your idea is to let Phpunit display errors when coding standards is incorrect?

Just out of curiosity, I hope the IE in your nickname has nothing to do with Internet Explorer :D

**Comment by BrianHenryIE** [comment]
I use Terminal a lot for PHPCS and PHPUnit. But you should try out PhpStorm rather than Sublime anyway! PHPCS is the tool to display the coding standards errors. They're generally small formatting issues but it does highlight some security issues too, e.g. nonce checking. When I send a PR for the coding standards branch I have (which I haven't worked on recently) they'll all be fixed! If your IDE is set up for PHPCS it will highlight lines that don't adhere to the standards. PHPUnit is unrelated to the coding standards, it's to verify the output of your code, e.g. I wrote code yesterday to [configure PhpStorm from composer](https://github.com/BrianHenryIE/composer-phpstorm/blob/master/tests/ExcludeFoldersTest.php), where I'm verifying the messages logged are the ones expected and the XML output is correct (by comparing to a file expected.xml)

I [forked WordPress Plugin Boilerplate](https://github.com/BrianHenryIE/WordPress-Plugin-Boilerplate/) recently – and included this project as part of it – try follow my instructions and hopefully it will set everything up easy for you!

IE is the TLD for Ireland! www.BrianHenry.ie

**Pull request merged**
